POST http://[::1]:3000/clientes/1/transacoes HTTP/1.1
Content-Type: application/json

{
  "valor": 1,
  "tipo": "c",
  "descricao": "kVO4lFggTM"
}

###

GET http://[::1]:9999/clientes/5/extrato HTTP/1.1
Content-Type: application/json