POST http://localhost:9999/clientes/1/transacoes HTTP/1.1
Content-Type: application/json

{
  "valor": 1,
  "tipo": "c",
  "descricao": "validacao"
}

###

GET http://localhost:9999/clientes/1/extrato HTTP/1.1
Content-Type: application/json